#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.38.20:3306/themis_admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: themis_admin
      password: WKSorogljayQYG8o
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  jackson:
    time-zone: GMT+8

  redis:
      #数据库索引
      database: 2
      host: 192.168.38.35
      port: 6379
      password: DdsWib6LFV2gB2a6
      #连接超时时间
      timeout: 5000
      jedis:
        pool:
          #最大连接数
          max-active: 100
          #最大阻塞等待时间(负数表示没限制)
          max-wait: 2000
          #最大空闲
          max-idle: 500
          #最小空闲
          min-idle: 8



#jwt
jwt:
  header: Authorization
  secret: hermes_themis_sit_201200221
  # token 过期时间 20个小时
  expiration: 72000000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info
  sso:
    host: http://sso.hupu.io


#是否开启 swagger-ui
swagger:
  enabled: true

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  type-enums-package: com.hupu.themis.admin.system.enums
  type-aliases-package: com.hupu.themis.admin.*.domain
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false




