#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp15dja9u7b854304.mysql.rds.aliyuncs.com/themis_admin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: themis_admin
      password: Ycda2jCkO00S7QYq8b0Z6FGZ
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: sdfsfsfsfdswq3r23r
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置Redis
  redis:
      #数据库索引
      database: 0
      host: r-bp1f0d1eb8a2b4e4.redis.rds.aliyuncs.com
      port: 6379
      password: r-bp1f2c01f84e9a14:jUjsF1J9zJDTMpzX
      #连接超时时间
      timeout: 5000
      jedis:
        pool:
          #最大连接数
          max-active: 100
          #最大阻塞等待时间(负数表示没限制)
          max-wait: 2000
          #最大空闲
          max-idle: 500
          #最小空闲
          min-idle: 8

#jwt
jwt:
  header: Authorization
  secret: hermes_themis_prd_201200221
  # token 过期时间 20个小时
  expiration: 72000000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info
  sso:
    host: http://sso.hupu.io

#是否开启 swagger-ui
swagger:
  enabled: false

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  type-enums-package: com.hupu.themis.admin.system.enums
  type-aliases-package: com.hupu.themis.admin.*.domain
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:
      table-underline: true
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false

